class AIXSequencesError(Exception): ...
class AIXUnserializeObjectError(Exception): ...
class AIXVectorizerNotFoundError(FileNotFoundError): ...
class AIXModelNotFoundError(FileNotFoundError): ...
class AIXInvalidVectorTypeError(Exception): ...
